spring:
  mail:
    host: smtp.gmail.com
    username: jauharisumit0@gmail.com
    password: Sumit123@
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
            auth: true
            connectiontimeout: 5000
            timeout: 10000
            writetimeout: 5000